name: CI - Jest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --appendonly yes

    env:
      REDIS_URL: redis://localhost:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node"

      - name: Install MongoDB Binary
        run: |
          wget -qO- https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.5.tgz | tar -zx
          sudo mv mongodb-linux-x86_64-ubuntu2004-6.0.5/bin/* /usr/local/bin/

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
        env:
          REDIS_URL: redis://localhost:6379
          MONGOMS_SYSTEM_BINARY: /usr/local/bin/mongod # Path to the MongoDB binary
